version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=security_system
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d security_system"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - security_system_network

  gateway:
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    environment:
      - API_SERVICE_URL=http://api:8000
      - JWT_SECRET=a-secure-secret-for-jwt-that-is-long-and-random
    networks:
      - security_system_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - security_system_network

  api:
    build:
      context: ./src/api
    container_name: api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/api:/home/appuser/app/src
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - STORAGE_BACKEND=minio # or 'local'
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=security-system
    networks:
      - security_system_network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - security_system_network

  stream_processor:
    build:
      context: ./src/stream_processor
    container_name: stream_processor
    depends_on:
      - timescaledb
    volumes:
      # - ./src:/app/src
      - hls_data:/media/hls
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=src.api.core.settings
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=security_system
      - ZMQ_PUB_URL=tcp://*:5555
      - RTSP_URLS=rtsp://user:password@192.168.1.64:554/Streaming/Channels/101,rtsp://user:password@192.168.1.64:554/Streaming/Channels/201,rtsp://user:password@192.168.1.64:554/Streaming/Channels/301
    networks:
      - security_system_network

  person_detector:
    build:
      context: ./src/person_detector
    container_name: person_detector
    depends_on:
      - stream_processor
    environment:
      - ZMQ_SUB_URL=tcp://stream_processor:5555
      - ZMQ_PUB_URL=tcp://*:5556
      - MIN_CONTOUR_AREA=500
    networks:
      - security_system_network

  event_handler:
    build:
      context: ./src/event_handler
    container_name: event_handler
    depends_on:
      - person_detector
      - timescaledb
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=src.api.core.settings
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=security_system
      - ZMQ_SUB_URL=tcp://person_detector:5556
    networks:
      - security_system_network

volumes:
  timescaledb_data:
  redis_data:
  minio_data:
  hls_data:

networks:
  security_system_network:
    driver: bridge
