# Generated by Django 4.2 on 2026-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='livestream',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('camera',), name='unique_active_stream_per_camera'),
        ),
    ]
