# Generated by Django 4.2 on 2026-04-30 03:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_zones', to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(default='person', max_length=50)),
                ('min_confidence', models.DecimalField(decimal_places=3, default=0.7, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('cooldown_seconds', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detections.detectionzone')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('snapshot_object_key', models.TextField(blank=True, null=True)),
                ('frame_ts', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_events', to='cameras.camera')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.detectionzone')),
            ],
            options={
                'unique_together': {('id', 'time')},
            },
        ),
    ]
